# === Begin DCT + Zigzag frequency analysis ===
import numpy as np
from scipy.fftpack import dct
import matplotlib.pyplot as plt
import torch
from tqdm import tqdm
import random

def dct2(block):
    """Compute 2D DCT (type II) on a block."""
    return dct(dct(block.T, norm='ortho').T, norm='ortho')

def zigzag_indices(n):
    """Generate zigzag order indices for an n x n matrix."""
    indices = np.empty((n * n, 2), dtype=int)
    index = -1
    for s in range(2 * n - 1):
        if s % 2 == 0:
            for i in range(s + 1):
                j = s - i
                if i < n and j < n:
                    index += 1
                    indices[index] = [i, j]
        else:
            for i in range(s + 1):
                j = s - i
                if i < n and j < n:
                    index += 1
                    indices[index] = [j, i]
    return indices

def compute_frequency_profile(latents, block_size=8):
    """
    Compute the average frequency profile over all latent maps using blockwise DCT.
    The profile is generated by taking the normalized DCT coefficients in zigzag order.
    
    Args:
        latents (torch.Tensor): latent tensor of shape (B, C, H, W).
        block_size (int): size of the block to compute DCT on.
        
    Returns:
        np.ndarray: 1D array containing the average normalized amplitude per zigzag index.
    """
    # Convert latents to numpy array (assuming they are on CPU or move them)
    latent_np = latents.detach().cpu().numpy()
    B, C, H, W = latent_np.shape
    zigzag_idx = zigzag_indices(block_size)
    profiles = []
    
    for b in range(B):
        for c in range(C):
            latent_map = latent_np[b, c]
            blocks = []
            # Divide latent map into non-overlapping blocks of size block_size x block_size
            for i in range(0, H, block_size):
                for j in range(0, W, block_size):
                    block = latent_map[i:i+block_size, j:j+block_size]
                    # Only process complete blocks
                    if block.shape == (block_size, block_size):
                        dct_block = dct2(block)
                        # Normalize: compute the normalized amplitude relative to the DC component (D[0,0])
                        dc = np.abs(dct_block[0, 0]) + 1e-8  # avoid division by zero
                        normalized_block = np.abs(dct_block) / dc
                        # Reorder coefficients in zigzag order
                        zz = normalized_block[zigzag_idx[:, 0], zigzag_idx[:, 1]]
                        blocks.append(zz)
            if blocks:
                # Average over all blocks in this channel
                channel_profile = np.mean(blocks, axis=0)
                profiles.append(channel_profile)
    
    if profiles:
        # Average over all channels and samples
        return np.mean(profiles, axis=0)
    else:
        return None

def smooth_data(data, window_size=5):
    """
    Apply a moving average smoothing to the data.
    
    Args:
        data (np.ndarray): 1D array to smooth.
        window_size (int): Size of the smoothing window.
        
    Returns:
        np.ndarray: Smoothed data.
    """
    window = np.ones(window_size) / window_size
    return np.convolve(data, window, mode='valid')

def smooth_data_with_std(data, window_size=5):
    """
    Apply a moving average smoothing to the data and calculate standard deviation.
    
    Args:
        data (np.ndarray): 1D array to smooth.
        window_size (int): Size of the smoothing window.
        
    Returns:
        tuple: (smoothed_data, std_deviation)
    """
    window = np.ones(window_size) / window_size
    smoothed = np.convolve(data, window, mode='valid')
    
    # Calculate standard deviation for the confidence interval
    std_dev = np.zeros_like(smoothed)
    half_window = window_size // 2
    
    for i in range(len(smoothed)):
        # Get the window of original data that corresponds to this smoothed point
        start_idx = max(0, i - half_window)
        end_idx = min(len(data), i + half_window + 1)
        window_data = data[start_idx:end_idx]
        # Calculate standard deviation for this window
        std_dev[i] = np.std(window_data)
    
    return smoothed, std_dev

def compute_global_dc(tensor, block_size=8):
    """
    Compute the global average of the DC components (D[0,0]) 
    over all blocks for all channels in the tensor.
    
    Args:
        tensor (torch.Tensor): Input tensor of shape (B, C, H, W).
        block_size (int): Block size used for computing the DCT.
        
    Returns:
        float: Global average of DC components.
    """
    np_tensor = tensor.detach().cpu().numpy()
    B, C, H, W = np_tensor.shape
    dc_values = []
    
    for b in range(B):
        for c in range(C):
            feature_map = np_tensor[b, c]
            for i in range(0, H, block_size):
                for j in range(0, W, block_size):
                    block = feature_map[i:i+block_size, j+j+block_size]
                    if block.shape == (block_size, block_size):
                        dct_block = dct2(block)
                        dc_values.append(np.abs(dct_block[0, 0]))
    return np.mean(dc_values) if dc_values else 1.0

if __name__ == "__main__":
    # Set random seeds for reproducibility
    seed = 42  # You can change this to any integer
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False
    
    with torch.no_grad():
        from diffusers import AutoencoderKL
        from vae_finetune_diffusability import ImageDataset
        from torch.utils.data import DataLoader
        device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
        
        # Process images with your VAE that has scale equivariance
        vae_with_se = AutoencoderKL.from_pretrained("/mnt/share/Luigi/Documents/URAE/vae_finetuning/vae-finetuned/").to(device)
        vae_without_se = AutoencoderKL.from_pretrained(
                "black-forest-labs/FLUX.1-dev",
                subfolder="vae",
                revision=None,
        ).to(device)
        
        dataset = ImageDataset("/mnt/share/datasets/img_align_celeba", image_size=256)
        dataloader = DataLoader(
            dataset, 
            batch_size=32, 
            shuffle=False,  # With fixed seed and shuffle=False, we'll always get the same images
            num_workers=4
        )

        # Configuration flags
        total_images = 100
        smoothing_enabled = True
        log_scale_enabled = True
        single_image_analysis = True  # Flag to analyze individual images
        num_images_to_analyze = 8     # Analyze 8 different images
        block_sizes = [8, 16]         # Focus on specific block sizes for single image analysis
        
        if single_image_analysis:
            # Get a batch to sample individual images from
            batch = next(iter(dataloader))
            images = batch["pixel_values"].to(device)
            
            for block_size in tqdm(block_sizes):
                # Create a figure with subplots for all images
                fig, axs = plt.subplots(num_images_to_analyze, 2, figsize=(16, 4 * num_images_to_analyze))
                
                for img_idx in range(num_images_to_analyze):
                    if img_idx >= len(images):  # Safety check
                        break
                        
                    single_image = images[img_idx:img_idx+1]  # Keep batch dimension
                    
                    # Process with both VAEs
                    encoded_with_se = vae_with_se.encode(single_image)
                    latents_with_se = encoded_with_se.latent_dist.sample()
                    
                    encoded_without_se = vae_without_se.encode(single_image)
                    latents_without_se = encoded_without_se.latent_dist.sample()
                    
                    # Compute frequency profiles for single image
                    fp_with_se = compute_frequency_profile(latents_with_se, block_size=block_size)
                    fp_without_se = compute_frequency_profile(latents_without_se, block_size=block_size)
                    fp_rgb = compute_frequency_profile(single_image, block_size=block_size)
                    
                    if fp_with_se is not None and fp_without_se is not None and fp_rgb is not None:
                        # Plot frequency profiles for single image
                        axs[img_idx, 0].plot(fp_with_se, label='With SE', color='blue')
                        axs[img_idx, 0].plot(fp_without_se, label='Without SE', color='orange')
                        axs[img_idx, 0].plot(fp_rgb, label='RGB', color='green')
                        
                        axs[img_idx, 0].set_xlabel("Zigzag Frequency Index")
                        axs[img_idx, 0].set_ylabel("Normalized Amplitude")
                        axs[img_idx, 0].set_title(f"Image {img_idx+1} DCT Spectrum")
                        if log_scale_enabled:
                            axs[img_idx, 0].set_yscale('log')
                        axs[img_idx, 0].grid(True, which="both", ls="-")
                        if img_idx == 0:  # Only add legend to the first plot to save space
                            axs[img_idx, 0].legend()
                        
                        # Show the image being analyzed
                        img_np = single_image[0].permute(1, 2, 0).cpu().numpy()
                        img_np = (img_np + 1) / 2.0  # Denormalize if needed
                        img_np = np.clip(img_np, 0, 1)
                        axs[img_idx, 1].imshow(img_np)
                        axs[img_idx, 1].set_title(f"Image {img_idx+1}")
                        axs[img_idx, 1].axis('off')
                
                plt.tight_layout()
                plt.savefig(f"8_images_dct_spectrum_bs_{block_size}.png")
                plt.close()
                
                # Additional focused analysis - create individual plots for better detail
                for img_idx in range(num_images_to_analyze):
                    if img_idx >= len(images):
                        break
                        
                    single_image = images[img_idx:img_idx+1]
                    
                    # Process with both VAEs
                    encoded_with_se = vae_with_se.encode(single_image)
                    latents_with_se = encoded_with_se.latent_dist.sample()
                    
                    encoded_without_se = vae_without_se.encode(single_image)
                    latents_without_se = encoded_without_se.latent_dist.sample()
                    
                    # Compute frequency profiles for single image
                    fp_with_se = compute_frequency_profile(latents_with_se, block_size=block_size)
                    fp_without_se = compute_frequency_profile(latents_without_se, block_size=block_size)
                    fp_rgb = compute_frequency_profile(single_image, block_size=block_size)
                    
                    if fp_with_se is not None and fp_without_se is not None and fp_rgb is not None:
                        plt.figure(figsize=(10, 8))
                        
                        # Create a 2x1 subplot layout
                        plt.subplot(2, 1, 1)
                        plt.plot(fp_with_se, label='With Scale Equivariance', color='blue')
                        plt.plot(fp_without_se, label='Without Scale Equivariance', color='orange')
                        plt.plot(fp_rgb, label='RGB Input', color='green')
                        
                        plt.xlabel("Zigzag Frequency Index")
                        plt.ylabel("Normalized Amplitude")
                        plt.title(f"Image {img_idx+1} DCT Spectrum - Block size {block_size}")
                        if log_scale_enabled:
                            plt.yscale('log')
                        plt.grid(True, which="both", ls="-")
                        plt.legend()
                        
                        # Display the image
                        plt.subplot(2, 1, 2)
                        img_np = single_image[0].permute(1, 2, 0).cpu().numpy()
                        img_np = (img_np + 1) / 2.0
                        img_np = np.clip(img_np, 0, 1)
                        plt.imshow(img_np)
                        plt.title(f"Image {img_idx+1}")
                        plt.axis('off')
                        
                        plt.tight_layout()
                        plt.savefig(f"single_image_{img_idx+1}_dct_spectrum_bs_{block_size}.png")
                        plt.close()
        else:
            # Original batch processing code
            for block_size in tqdm(range(4, 32, 2)):
                total_processed = 0
                sum_fp_with_se = None
                sum_fp_without_se = None
                sum_fp_rgb = None

                for batch in tqdm(dataloader):
                    images = batch["pixel_values"].to(device)
                    curr_bs = images.size(0)
                    if total_processed + curr_bs > total_images:
                        images = images[: total_images - total_processed]
                        curr_bs = images.size(0)
                    total_processed += curr_bs

                    # For with SE
                    encoded = vae_with_se.encode(images)
                    latents_with_se = encoded.latent_dist.sample()
                    # For without SE
                    encoded = vae_without_se.encode(images)
                    latents_without_se = encoded.latent_dist.sample()

                    # Compute frequency profiles for current batch
                    fp_with_se = compute_frequency_profile(latents_with_se, block_size=block_size)
                    fp_without_se = compute_frequency_profile(latents_without_se, block_size=block_size)
                    fp_rgb = compute_frequency_profile(images, block_size=block_size)

                    if fp_with_se is not None and fp_without_se is not None and fp_rgb is not None:
                        if sum_fp_with_se is None:
                            sum_fp_with_se = fp_with_se * curr_bs
                            sum_fp_without_se = fp_without_se * curr_bs
                            sum_fp_rgb = fp_rgb * curr_bs
                        else:
                            sum_fp_with_se += fp_with_se * curr_bs
                            sum_fp_without_se += fp_without_se * curr_bs
                            sum_fp_rgb += fp_rgb * curr_bs
                    if total_processed >= total_images:
                        break

                final_fp_with_se = sum_fp_with_se / total_images
                final_fp_without_se = sum_fp_without_se / total_images
                final_fp_rgb = sum_fp_rgb / total_images

                if final_fp_with_se is not None and final_fp_without_se is not None and final_fp_rgb is not None:
                    if smoothing_enabled:
                        window_size = 10  # Adjust as needed
                        if (len(final_fp_with_se) > window_size and 
                            len(final_fp_without_se) > window_size and 
                            len(final_fp_rgb) > window_size):
                            
                            # Get smoothed data and standard deviation for shaded areas
                            smooth_profile_with_se, std_with_se = smooth_data_with_std(final_fp_with_se, window_size)
                            smooth_profile_without_se, std_without_se = smooth_data_with_std(final_fp_without_se, window_size)
                            smooth_rgb_profile, std_rgb = smooth_data_with_std(final_fp_rgb, window_size)
                            x_values = np.arange(len(smooth_profile_with_se))
                            
                            plt.figure(figsize=(10, 6))
                            
                            # Plot with shaded regions for each line
                            plt.plot(x_values, smooth_profile_with_se, label='With Scale Equivariance', color='blue')
                            plt.fill_between(x_values, 
                                            smooth_profile_with_se - std_with_se, 
                                            smooth_profile_with_se + std_with_se, 
                                            alpha=0.3, color='blue')
                            
                            plt.plot(x_values, smooth_profile_without_se, label='Without Scale Equivariance', color='orange')
                            plt.fill_between(x_values, 
                                            smooth_profile_without_se - std_without_se, 
                                            smooth_profile_without_se + std_without_se, 
                                            alpha=0.3, color='orange')
                            
                            plt.plot(x_values, smooth_rgb_profile, label='RGB Input', color='green')
                            plt.fill_between(x_values, 
                                            smooth_rgb_profile - std_rgb, 
                                            smooth_rgb_profile + std_rgb, 
                                            alpha=0.3, color='green')
                            
                            plt.xlabel("Zigzag Frequency Index")
                            plt.ylabel("Normalized Amplitude (log scale)")
                            plt.title(f"DCT Spectrum Comparison (Log Scale with Smoothing) - Block size {block_size}")
                            if log_scale_enabled:
                                plt.yscale('log')
                            plt.grid(True, which="both", ls="-")
                            plt.legend()
                            plt.savefig(f"dct_spectrum_log_smooth_bs_{block_size}.png")
                            plt.close()
                        else:
                            plt.figure(figsize=(10, 6))
                            plt.plot(final_fp_with_se, label='With Scale Equivariance')
                            plt.plot(final_fp_without_se, label='Without Scale Equivariance')
                            plt.plot(final_fp_rgb, label='RGB Input')
                            plt.xlabel("Zigzag Frequency Index")
                            plt.ylabel("Normalized Amplitude (log scale)")
                            plt.title(f"DCT Spectrum Comparison (Log Scale) - Block size {block_size}")
                            if log_scale_enabled:
                                plt.yscale('log')
                            plt.grid(True, which="both", ls="-")
                            plt.legend()
                            plt.savefig(f"dct_spectrum_log_bs_{block_size}.png")
                            plt.close()
                    else:
                        plt.figure(figsize=(10, 6))
                        plt.plot(final_fp_with_se, label='With Scale Equivariance')
                        plt.plot(final_fp_without_se, label='Without Scale Equivariance')
                        plt.plot(final_fp_rgb, label='RGB Input')
                        plt.xlabel("Zigzag Frequency Index")
                        plt.ylabel("Normalized Amplitude (log scale)")
                        plt.title(f"DCT Spectrum Comparison (Log Scale) - Block size {block_size}")
                        if log_scale_enabled:
                            plt.yscale('log')
                        plt.grid(True, which="both", ls="-")
                        plt.legend()
                        plt.savefig(f"dct_spectrum_log_bs_{block_size}.png")
                        plt.close()
                else:
                    print(f"One or more frequency profiles could not be computed for block size {block_size}.")
